### PR TITLE
✨ Improve README.md

### PR DESCRIPTION
**Pull request by newtoallofthis123**
So I tried to modify the README.md for the project using the main [withastro/docs](https://github.com/withastro/docs/) as a template since I wasn't sure what template to use.

Please suggest any and all changes to anything from my English to any adding new sections. Thanks :)

### CODE REVIEW

**Comment by Princesseuh** [comment]
Thank you, I'll review this as soon as possible!

**Comment by newtoallofthis123** [comment]
Sure

**Review by Princesseuh — APPROVED** [review]
Thank you, this looks great! I just slightly rewrote some parts, but most of it was already perfect.

**Comment by newtoallofthis123** [comment]
Thanks 😄

**Pull request merged**
