### PR TITLE
Fix Sponsors Color Issue

### PR DESCRIPTION
**Pull request by newtoallofthis123**
The main error was caused by the fact that the svg's were being imported in the `<Image>` component which I think preprocesses the svg which is where I think the `#sponser-icon` id was being redundant.

So, the only way I saw to solve it without too much interference was to just embed the svg's in the component itself. Also, I saw that in the main Astro docs, a similar thing was being done. So I took the liberty to essentially copy and paste the svg's. 

It works perfectly rn 
Light Mode Works!

I also checked if it affected the component load speed and such: It does by about `15ms`.  

Note that I didn't delete the svg's because I wasn't sure. So what do you guys think? Is this a good idea?

Hopes to solve #3

### CODE REVIEW

**Comment by DanielTolentino** [comment]
Yep, I tried almost everything, but I got nothing when trying to style the Image component with SVGs inside. Your approach works fine.

**Comment by newtoallofthis123** [comment]
Yeah exactly! I think the preprocessing makes the id redundant. One approach is to css invert the image, but that would destroy the brand logo. Hence I thought the svg's were the best option

**Comment by DanielTolentino** [comment]
Yep, I tried `filter: invert(100%) !important;` too, but it breaks logo colors.

**Comment by newtoallofthis123** [comment]
Same 😅

**Comment by Princesseuh** [comment]
This seems fine to me, especially since eventually I'd hope to replace this component with a native Starlight one! You can go ahead and delete the .svgs in the folder, it's fine

**Comment by newtoallofthis123** [comment]
Cool! I'll do that and commit

**Review by Princesseuh — APPROVED** [review]
Looks great, thank you!

**Comment by newtoallofthis123** [comment]
Oh! Makes sense to use `Fragment`! Hadn't thought of that 😄

**Comment by delucis** [comment]
Noting that the StackBlitz and Vue logo SVGs are missing `width` attributes (or have `width="auto"` so aren’t displaying currently:

Sponsors component showing only Nuxt and Prefect

Maybe someone here would like to make a PR adding a `width` to the `<svg>` element in those two files?

**Comment by newtoallofthis123** [comment]
Sure!

**Comment by Princesseuh** [comment]
Oh weird, they show up fine in my browser

**Comment by delucis** [comment]
Ah yeah, looks fine in Chrome. Broken in Safari and Firefox. Should have specified sorry!

**Comment by newtoallofthis123** [comment]
Lucky I use firefox then 😄

**Pull request merged**
